### ISSUE TITLE
headerデザインの変更

### ISSUE THREAD

**Issue by reitanoue** [Y-K-15/Moshalympics-teamC#28]
# やってほしいこと
・ボックスシャドウをつける
・POSSEの部分だけ本家のロゴにして、2の部分は手打ちにする

# まだやらないでほしいこと
・ナビゲーションのデザイン（#19）にすること

**Comment by Y-K-15** [comment]
#40  についても対応中です。

**Comment by Y-K-15** [comment]
レスポンシブ対応のことも考えるとヘッダーの高さとかをpxで指定するのよくないと思っております。そうするとなると「やってほしいこと」の　「２」を手打ちにするっていうのやるのがいろいろ面倒になります。ですから、posseロゴと２を並べたものを画像として用意することで対応していきたいと思う所存。

**Comment by Y-K-15** [comment]
もともと透過画像のposseロゴを適当にPowerPointで２って追加したら透過画像じゃなくなっちゃったよ。かなしい。

**Comment by Y-K-15** [comment]
#39 #40も同時にやりました。
