### ISSUE TITLE
ハンバーガーメニューのheightを45pxに合わせる

### ISSUE THREAD

**Issue by reitanoue** [Y-K-15/Moshalympics-teamC#39]
🍔メニューのheightが44pxのままだと、三本線の3本目が細くなるのでそれを45pxにしてほしい

**Comment by Y-K-15** [comment]
レスポンシブ対応のためにpxでサイズ指定するのをやめたい[（参照）](https://github.com/Y-K-15/Moshalympics-teamC/issues/28#issuecomment-1034924480)のでこれも別のやり方で対応したい。今のところまったく分からんのだけども。

**Comment by Y-K-15** [comment]
レスポンシブとりあえず諦めた。

**Comment by Y-K-15** [comment]
レスポンシブの方法を別のやり方に変えるって感じでやるcar
土曜日中までにやります

**Comment by Y-K-15** [comment]
#28 に統合しました
